### ISSUE TITLE
$eq operator is broken with certain string values

### ISSUE THREAD

**Issue by aberonni** [ppetzold/nestjs-paginate#1000]
## Steps to reproduce

Perform a filter query with an `$eq` filter with a string that contains "what JS believes to be a number, but that is actually a string"™

For example, `filter.referenceId` = `$eq:651581942751358e5`

## Expected result

Elements with the given filter are found.

## Actual result

No elements are found

## Additional notes

This regression was introduced in #952. It happens because the above string passes the `Number.isNumber` check, even though the value is not _meant_ to be a number.

In the example above:

```js
const myString = '651581942751358e5'
console.log(Number.isNaN(myString)) // false
console.log(Number(myString)) // 65158194275135800000
```

The `Number()` conversion is not problematic with values that are actually numbers - but unfortunately JS has a loose interpretation of [which strings actually qualify as numbers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#convert_numeric_strings_and_null_to_numbers).

**Comment by aberonni** [comment]
@Helveg thanks for getting back to me. I opened a PR with what might be a way to address this. Let me know what you think.

**Comment by Helveg** [comment]
We could fix this by treating strings with leading zeros as strings and not numbers.

**Comment by aberonni** [comment]
Sounds like there could be more potential edge cases out there. I can't help but feel that perhaps this should be handled differently. Perhaps, type coercion / casting should be opt-in, so that it doesn't happen at all unless the user asks for it - that would avoid having to cater for edge cases in the nestjs-paginate code.

**Comment by Helveg** [comment]
Yea, there's similar problems with treating booleans and null (see a couple of other open issues). I think since we use `:` as separator, we could allow appending `::number` and similar for type casting, pgsql style. That gives more control. Another approach is to go by TypeORM column type.

**Comment by aberonni** [comment]
> One approach is to go by TypeORM column type perhaps?

That does indeed sound ideal. I'll try and see if that's easy for me to implement in the open PR.

**Comment by aberonni** [comment]
@Helveg I had a quick look and couldn't see an easy/obvious way to implement this. Let me know if you have time to take a look, if not then I will invest more time in digging.

**Comment by Helveg** [comment]
You can propagate the `SelectQueryBuilder` from the parent function and use the `qb.expressionMap.mainAlias.metadata` to get the entity metadata, from there it's typical TypeORM metadata manipulation. `findRelationWithPropertyPath`and `findColumnWithPropertyPath` might be useful :)

You can find columns/relations quite easily, but I'm not sure how easy it is to deal with nested relationships and columns. I'm sure that somewhere else in the codebase we deal with this already.
