### ISSUE TITLE
How to use nestjs-paginate with limiting the query fields results?

### ISSUE THREAD

**Issue by arvindsedha** [ppetzold/nestjs-paginate#114]
is there a way to defind /cats?fields=field1,field2 etc?  ats the movement even using some custom solution?

E.g. provide also somehow FindOneOptions options when calling 

paginate(query, this.repository, config);

**Comment by ppetzold** [comment]
Doesn't currently exist for repositories. You could use `QueryBuilder` as a workaround.

But..

Allowing query to pass fields onto `FindOptions` would probably be an easy and straightforward solution.

**Helper config:**
```typescript
paginate(query, this.usersRepository, {
    sortableColumns: ['id', 'username', 'email', 'created'],
    select: ['id', 'username', 'email', 'firstName', 'lastName', 'created']
})
```
Select may acts as a whitelist for the query string here as well.

**Query string:**
```
/users?select=email,created
```
PK might be always selected.

_Happy to accept PR :)_
