### ISSUE TITLE
Swagger integration

### ISSUE THREAD

**Issue by 20Koen02** [ppetzold/nestjs-paginate#173]
It would be nice to have swagger documentation support for the parameters. Currently it's not possible to change the limit, page or filter on the docs page.

**Comment by 20Koen02** [comment]
Crude way I (partially) solved it:
![Screenshot from 2022-02-25 16-28-24](https://user-images.githubusercontent.com/33985194/155741983-8724b9ae-ef04-4897-8a38-4685b68e0f88.png)

**Comment by ppetzold** [comment]
true. some helper would be sweet

**Comment by frankforpresident** [comment]
@20Koen02 

I've created a custom decorator as a temporary solution. Works great

```
import { applyDecorators } from '@nestjs/common';
import { ApiQuery } from '@nestjs/swagger';

export function PaginateQueryOptions() {
  return applyDecorators(
    ApiQuery({ name: 'page', required: false }),
    ApiQuery({ name: 'limit', required: false }),
    ApiQuery({ name: 'search', required: false }),
    ApiQuery({ name: 'sortBy', required: false }),
    ApiQuery({ name: 'filter', required: false }),
  );
}
```

**Comment by TheToto** [comment]
Here is a decorator that al generate a correct response schema.

https://gist.github.com/TheToto/f29a8479393846b47961b2c8397a8217

**Comment by ppetzold** [comment]
> Here is a decorator that also generate a correct response schema, based on above answers
> 
> https://gist.github.com/TheToto/f29a8479393846b47961b2c8397a8217

Good stuff ! Filter spec could be improve somewhat (see examples in https://github.com/ppetzold/nestjs-paginate#filters).

Also happy to accept a PR with swagger helpers ;)
