### ISSUE TITLE
Sort nested fields for query builders

### ISSUE THREAD

**Issue by chrysovalantis** [ppetzold/nestjs-paginate#180]
Currently, sortable columns inside the config must be fields of the given entity. However, If the field is a joined entity, you cannot select a nested field for sorting. 

**Example:**
```
TaskEntity {                           UserEntity {  
   id: number,                             id: number,                
   title: string,                          firstName: string,
   createdBy: User                         lastName: string
}                                      }
```
**Query:**
`await paginate<TaskEntity>(query, queryBuilder, { sortableColumns: ['title', 'createdBy.firstName', 'createdBy.lastName']});`

I am not allowed to select createdBy.firstName or createdBy.lastName as a sortable column because there are no direct fields of TaskEnitty. Do you have any solutions?

**Comment by ppetzold** [comment]
Nothing out-of-the-box. You could probably play with the query builder you pass onto the paginate function - but it might be easier to add extend this package.

Happy to accept a PR :)
