### ISSUE TITLE
How can i use $btw param with Date Format?

### ISSUE THREAD

**Issue by kangminsu2** [ppetzold/nestjs-paginate#190]
How can i use $btw param with Date Format?
i want to search with Date type params

**Comment by ppetzold** [comment]
On the URL side this usage would look like this:

```url
http://localhost:3000/cats?filter.createdAt=$btw:2022-01-01,2022-02-01
```

**Comment by kangminsu2** [comment]
thanks for your comment.
then Does datetime work in YYY-MM-DD format too?

**Comment by kangminsu2** [comment]
thanks a lot !!!

**Comment by kangminsu2** [comment]
thanks a lot !!!
then how to make datetime format param like YYYY-MM-DD:H24:mm:ss ?
