### ISSUE TITLE
It's possible to use ILIKE?

### ISSUE THREAD

**Issue by juniorduff** [ppetzold/nestjs-paginate#194]
Has any way to use ILIKE to filter data ? From query builder  TYPEORM.

**Comment by juniorduff** [comment]
![image](https://user-images.githubusercontent.com/23487781/159848961-db378385-3dc7-4e7a-9f2d-2f54906d056c.png)
My solution

**Comment by ppetzold** [comment]
You would need to ILIKE as a new filter operator. Happy to accept PR.

Alternatively, you can do a workaround with `?searchBy=title&search=foo`.
