### ISSUE TITLE
Swagger and PaginateQuery

### ISSUE THREAD

**Issue by Diaskhan** [ppetzold/nestjs-paginate#202]
Hi guyes.

1.There have some qestions about swagger and PaginateQuery.

I have filter function, and i want so that paramater work via POST query.
There  if define PaginateQuery with body decorator. I dont see incoming parameteres in swagger UI.
```
  @Post('filter')
  @ApiOperation({ summary: 'Получить данные фильтрация' })
  filter(@Body() query: PaginateQuery): Promise<Paginated<OrdersEntity>> {
    return this.findAll2(query);
  }
```
 
If I create another DTO
```

import { ApiProperty } from '@nestjs/swagger';

export class OrderCreateDTO {
  @ApiProperty({example: 'Sergey Mikhailov', description: 'ФИО'})  
  name: string;

  @ApiProperty({example: '123@mail.kz', description: 'E-mail'})
  email: string;
}

```
And make another type, this works.   but is not works out of box.
 ```
 @Post('filter')
  @ApiOperation({ summary: 'Получить данные фильтрация' })
  filter(@Body() query: PaginateQuery2): Promise<Paginated<OrdersEntity>> {

    var query2:PaginateQuery;
    query2=<PaginateQuery>query;
    return this.findAll2(query2);
  }
```

What Ure recomndations, and to make work via post ???

Because if there will be about 10 fields filtration, URL will be very ugly !!! 
http://localhost:3000/cats?limit=5&page=2&sortBy=color:DESC&search=i&filter.age=$gte:3

2.Questions is, i need swagger description, because I generate UI Angular code via ng-openapi-gen.
And i need described swagger definition!

**Comment by Diaskhan** [comment]
https://stackoverflow.com/questions/68460951/use-interface-as-a-swagger-schema-nestjs-dto

**Comment by dkrantsberg** [comment]
> There is a open issue for swagger support #173
> 
> Happy to accept a PR ;)
> 
> About the other question, not sure what you are exactly referring to with using POST. POST route do support query params as well - there shouldn't be an issue 🤔 But generally using POST route to retrieve listed items seems not quite right. Maybe reconsider?

In general you're correct. But we have a scenario where we need to support `$in` filtering with ~1000-2000 items, which exceeds query string limit. Sending `PaginateQuery` in the request body would solve this issue.

**Comment by ppetzold** [comment]
(1) either you parse the request on your own and pass the query object to `paginate()`

(2) or you could just hack the decorator usage to pass the req body. see decorator tests for howto: https://github.com/ppetzold/nestjs-paginate/blob/master/src/decorator.spec.ts
