### ISSUE TITLE
Does not search for deleted

### ISSUE THREAD

**Issue by LeonardoDB** [ppetzold/nestjs-paginate#215]
HELPPP

Hello I have several tables in my system with deletedAt, but the typeorm does not search if it has a defined date, it will only bring the data if it is null. But there is a flag **{ withDeleted: true }** which will return deleted and non-deleted records, how do I do it by nestjs-paginate

**Comment by ppetzold** [comment]
You cannot currently.

I would accept a PR adding `withDeleted: true` to `PaginateConfig`, and then extend the query builder with `.withDeleted()`

https://typeorm.io/select-query-builder#querying-deleted-rows

**Comment by LeonardoDB** [comment]
I would like to give you the Pull Request, could you give me permission to do so?

**Comment by ppetzold** [comment]
no need to give permissions. you can open pull requests on this repo from your fork. it's a default settings for public github repos ;)

**Comment by LeonardoDB** [comment]
Ok friend, I created the pull request. =)

**Comment by ppetzold** [comment]
closed with #219
