### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by jongomes** [ppetzold/nestjs-paginate#231]
![photo4949650226537409010](https://user-images.githubusercontent.com/57728651/171285954-73ce82d9-b797-4207-8637-aa9b495f1da7.jpg)

post here, but I've had enough and I haven't found a solution

example: 
tecnicos: [{ id: 1} , { id: 2}]
filter return [{id: 1}], need tecnicos complete

**Comment by jongomes** [comment]
for would be a temporary solution

**Comment by jongomes** [comment]
thanks for answering

I need it
![image](https://user-images.githubusercontent.com/57728651/171385993-798e3341-3d2a-463a-b47c-587f26e53ac5.png)

and i have this
![image](https://user-images.githubusercontent.com/57728651/171386088-df165bb5-d409-4d20-8df2-71ad3ffc9146.png)


ie when filtering relationship, it filters the parent structure ok,
but filters the child structure,

I wanted to filter by the daughter, and return it complete, only the father is affected

**Comment by jongomes** [comment]
Another topic
![image](https://user-images.githubusercontent.com/57728651/171387231-0d381295-9eee-4827-8114-6e2be5e23381.png)
should this work?

**Comment by ppetzold** [comment]
The filter is based on the parent. If you say `?filter.tecnicos.id=3` it means "give me all items which have a child tecnicos with id 3". you cannot filter the childs that way. unless you do some handling yourself on the result of this lib.

**Comment by jongomes** [comment]
![image](https://user-images.githubusercontent.com/57728651/171437484-e8ffd5a9-4688-44a6-87c7-2f5dc54a8a5c.png)
typeorm v0.3.6 work 
works as expected
![image](https://user-images.githubusercontent.com/57728651/171437774-9e905597-a910-42fc-9e99-2dd71c77335b.png)
with eager: true  [{ id: 1} , { id: 2}]
with eager: false [{id: 2 }]

ie it works as I wanted
