### ISSUE TITLE
Query dependent tables of a repository

### ISSUE THREAD

**Issue by FlyingOddo** [ppetzold/nestjs-paginate#232]
I have a many to many relation between two tables (Customer, Documents)
  @ManyToMany(() => Document)
  @JoinTable()
  documents: Document[];

Now I want to get all Documents by Customer paginated. Is there a smart solution for this case? 

My workaround is to create the reference table by myself and use the repository of the reference table.

**Comment by FlyingOddo** [comment]
Thank you for your fast respond!
Does this also work if I only have a manytomany relation in in my Customer entity. There is no Customer field in the document entity. I also want to use them independently from the customers.

**Comment by ppetzold** [comment]
Havn't used typeorm for quite some time, lol. But it seems so:

https://typeorm.io/many-to-many-relations#loading-many-to-many-relations
