### ISSUE TITLE
Support for typeorm 0.3.0

### ISSUE THREAD

**Issue by jakobwgnr** [ppetzold/nestjs-paginate#239]
Currently typeorm peer dependency is set to <0.3.0.
As nestjs-typeorm v8.1.0 uses typeorm v0.3+ instead of v0.2+ it would be great to also upgrade here in order to fully migrate to 0.3+

Thanks, Jakob

**Comment by ppetzold** [comment]
yep. don't find the time atm. happy to accept PR :)
