### ISSUE TITLE
Filter does not work with QueryBuilder

### ISSUE THREAD

**Issue by FlyingOddo** [ppetzold/nestjs-paginate#250]
If I use a querybuilder, the filters doesnt work. Is this not supported by default?

**Comment by FlyingOddo** [comment]
The problem here is that the filter is attached to the where clause at the end. Using an orWhere can lead to problems. As a workaround, I only used a where clause and separated it from the added filter with addittional brackets.

**Comment by ppetzold** [comment]
hi there, filter using query builder isn't currently covered by any test - but it might work. could you elaborate in more detail the issue? (code lines + generated SQL)

**Comment by ppetzold** [comment]
works. see https://github.com/ppetzold/nestjs-paginate/commit/ab24b887025313a4e5d12ac532ab0bad1e13c7d9

**Comment by wisac** [comment]
Am I the only one still facing this issue in 2025?
Filter stops working when using query builder with a `orWhere` clause just like @MaximilianOtto  mentioned
