### ISSUE TITLE
Sorting by NULL LAST

### ISSUE THREAD

**Issue by jhrncar** [ppetzold/nestjs-paginate#267]
Hello,

Correct me if I am wrong, but there is currently no way to define in sortableColumns config, that null records should be sorting as last and not first.

![image](https://user-images.githubusercontent.com/71822106/178480891-eb845a04-2487-452e-bc0c-fc2e52c254ba.png)
![image](https://user-images.githubusercontent.com/71822106/178480959-13b15b5e-7b54-482c-a1da-0486162dbbf7.png)

If anyone has any workaround, feel free to correct me <3

Thanks!

**Comment by ppetzold** [comment]
https://chiayupai.medium.com/typeorm-orderby-nulls-last-w-mysql-4e35af85fe2

Happy to accept PR :)

**Comment by Elbarae1921** [comment]
Seeing as how there hasn't been much activity on this, I took the liberty of submitting a PR #296.
