### ISSUE TITLE
Filter not working on boolean

### ISSUE THREAD

**Issue by usamasaif** [ppetzold/nestjs-paginate#339]
export const CATEGORY_AVAILABLE_FILTERS = {
  isActive: [FilterOperator.EQ],
};

//postman
http://127.0.0.1:3000/api/v1/categories?search=rice&filter.isActice=true

//response getting
 data: [
    Category {
      id: 64,
      name: 'Rice 1',
      description: null,
      isActive: true,
      createdAt: 2022-09-23T09:55:59.141Z
    },
    Category {
      id: 63,
      name: 'rice',
      description: 'Best rice in the town........',
      isActive: false,
      createdAt: 2022-09-23T07:37:44.347Z
    }
  ],
  meta: {
    itemsPerPage: 20,
    totalItems: 2,
    currentPage: 1,
    totalPages: 1,
    sortBy: [ [Array] ],
    search: 'rice',
    searchBy: [ 'name' ],
    filter: { isActice: 'true' }
  },
  links: {
    first: undefined,
    previous: undefined,
    current: 'http://127.0.0.1:3000/api/v1/categories?page=1&limit=20&sortBy=id:DESC&search=rice&filter.isActice=true',
    next: undefined,
    last: undefined
  }
}

**Comment by ppetzold** [comment]
Good find. Will try to have a look these days.

**Comment by briandiaz** [comment]
@usamasaif I can see that you have a typo in your filter parameter.
It should be `isActive` and you have it as `isActice`.

Hope that helps.

**Comment by andrewhamili** [comment]
![image](https://github.com/user-attachments/assets/d2c7d62d-3e97-4ccb-bc32-37d77fd84202)
![image](https://github.com/user-attachments/assets/5c24bc38-a077-4dc9-95d4-c21dc35cb4ac)


I was implementing a filter for boolean but the above code does not work as expected.

![image](https://github.com/user-attachments/assets/93a5fc6a-599f-495c-afc0-fe8531da1c07)
![image](https://github.com/user-attachments/assets/600a38a0-0115-46df-adb3-eb2be47d8eb9)
