### ISSUE TITLE
Error for columns defined as enum when search

### ISSUE THREAD

**Issue by jakobwgnr** [ppetzold/nestjs-paginate#436]
Hello ! 
I get an error when trying to search for a property defined as enum. 
I think this is the reason why: https://stackoverflow.com/questions/35072844/using-ilike-on-an-enum-in-sql

here the created SQL-Statement:
WHERE ...  OR \"user\".\"role\" ILIKE $3  ... 

	"parameters": [
		"%Admin%",
		"%Admin%",
		"%Admin%",
		"%Admin%"
	],

I received following error...
	"driverError": {
		"length": 214,
		"name": "error",
		"severity": "ERROR",
		"code": "42883",
		"hint": "No operator matches the given name and argument types. You might need to add explicit type casts.",
		"position": "3319",
		"file": "parse_oper.c",
		"line": "731",
		"routine": "op_error"
	},

![image](https://user-images.githubusercontent.com/18501893/211150001-a5db84b1-efae-4efd-8aa3-1f0b68a4d3f8.png)

Hope you can help here.
BR Jakob

**Comment by ppetzold** [comment]
Looks like Postgres would require a string cast for enum comparison.

There is another issue with same problem and UUIDs.

I think, we might need to handle this separately for Postgres and cast all search columns to string. Or maybe even cast and concat all search columns and just perform a single ilike on the result.

...but actually, if TypeORM has a cast helper which works for all drivers. Then this should be preferable. So we don't need the branching.

Happy to accept a PR ;)

**Comment by jakobwgnr** [comment]
Hey Philipp!
Yea - Could also reproduce this error with typeorm only... so actually this isn't an issues for this package imho.. 

Couldn't find any cast helper from type orm, but here some possible solution.
https://stackoverflow.com/questions/68799728/typeorm-how-to-apply-where-like-on-entity-id

Wouldn't it also work if casting is done for all drivers in the proposed way? 

If this is a possible solution for you, then I could try my best to submit a PR :)

**Comment by ppetzold** [comment]
Yes, the raw method is the way too go. In this case we could do it for all as cast syntax and text data type seem to be the same on all sql dbs. The only nuance I could think of is that Postgres requires quoting for column names if they contain a capital letter. Not sure if quoting would be an issue for any of the other typeorm supported dbs tho 🤔

**Comment by ppetzold** [comment]
Fixed with #442
