### ISSUE TITLE
`defaultFilter` proposal

### ISSUE THREAD

**Issue by Helveg** [ppetzold/nestjs-paginate#448]
Often in medium sized projects, when you have multiple users/tenants and they query a `/resources` endpoint, they don't want to see all the resources on the application, but _their_ resources. This would mean that when I query `/resources` I'd like a default filter of `/resources?filter.user.id=$eq:authUserId`. It occurs often enough that I'd like to not have to specify it neither in the frontend query nor the backend controller logic.

I propose some additions to `PaginateConfig` that I can PR when we agree on the proposal:

* `defaultFilter` can be set to valid filters (see below).
* When `defaultFilter` is set, and there are no queried filters, `defaultFilter` is used. When queried filters are set, the `defaultFilter` is not applied.
* [bonus] `defaultFilterMode`: 
  * `FilterMode.defaultRemoved`: default dissapears when filters are set
  * `FilterMode.defaultCombined`: filters merged over default
  * `FilterMode.defaultAlwaysOn`: default filter merged with priority over query filters

Valid filters would be using the data structures `nestjs-paginate` uses to represent filters as produced by the `Paginate` param decorator. They currently don't seem specified, but from the source code it doesn't seem too complicated to write a spec and docs on them:

https://github.com/ppetzold/nestjs-paginate/blob/846569900e7f7aebee7a5ebf93177a5c57f7f0b7/src/decorator.ts#L53-L61

**Comment by ppetzold** [comment]
Hmm my first thoughts is that a "default filter" is kinda redundant with `where`. The filter modes seem like they would create a lot of magic on the endpoint - which might be hard to document (?)

> This would mean that when I query /resources I'd like a default filter of /resources?filter.user.id=$eq:authUserId

I think the common http/restful approach would be to have 2 endpoints

(1) `/resource`
(2) `/users/:userId/resource`

isn't it?

So not wanting to reject your proposal just yet 😅 maybe you could help me understanding by describing more use cases where this comes handy? The one you have given seems like an anti pattern to me.

**Comment by Helveg** [comment]
(1) Ayaaaaa, how did I miss that `where` could do this! I was very `filter` focused 😬 
(2) While very RESTful, I've never seen `/users/:userId/resource` in any REST API I've used. Let's take some big dogs, like Google, Amazon AWS, Stripe, ... none of them require me to scope my requests to my own user id, which as a end user I don't even know.

Let me reexamine the use cases taking the existence of `where` into account and get back to you!

**Comment by Helveg** [comment]
By creating a `where` clause for each request I can do anything I need it to do. Thanks for your swift attention!

**Comment by haydarai** [comment]
Hi, I would like to bring this conversation up again. My use case is something like this. I have an endpoint let's call it `/resources` and it has `status` column which indicate if a resource was activated/deactivated/etc. The idea is that we would like to only return `status = 'activated'` if no filter on `status` is specified and only return resources with all status if it's explicitly filtered that way. Is there any way to do this or the best way to apply this is if we can have `defaultFilter`? Thanks!

**Comment by Helveg** [comment]
You can do it using `where`:

```ts
const where = query.filters.status ? {} : { status: 'activated' }
return paginate(query, repo, {...config, where})
```

or something close to that
