### ISSUE TITLE
SQL Injection in search term 

### ISSUE THREAD

**Issue by ma-kassem** [ppetzold/nestjs-paginate#460]
Because of the template string in the query search. Using this library may cause SQL injection. Any untrusted input should be parameterized and some characters may have to be escaped 

![image](https://user-images.githubusercontent.com/113701618/214704333-fda6d1c2-6595-45ef-b644-9f82868aa3e0.png)

**Comment by FrancYescO** [comment]
https://github.com/ppetzold/nestjs-paginate/pull/442/files#r1081669412
