### ISSUE TITLE
API only returning subset of data in data array

### ISSUE THREAD

**Issue by Alfagun74** [ppetzold/nestjs-paginate#470]
I noticed some weird behaviour in my API today. 

It finds 372 Total items but the data array in the response only contains a single element. In other query-constellations sometimes only 2 to 5 elements show up, even though it should show at least 100.

- database log does not contain any errors
- nothing significant in the server-log
- the data in the database is also intact

It just seems to "cut off" the data. What could cause this bug?

With v4.7.0 i switched to the [Snake Case TypeORM Naming Strategy](https://www.npmjs.com/package/typeorm-naming-strategies). Could this be the cause? 

Issue exists in v4.7.0 and v4.8.0. I am using Postgres 15.1 and these dependenies:
```
"@nestjs/typeorm": "^9.0.1",
"typeorm": "^0.3.11",
"typeorm-naming-strategies": "^4.1.0",
```

Unfortunately The v4.6.X Versions and below don't seem to support Snake Case Naming Strategy and the SQL of it contains Syntax Errors.

The API:
```typescript
async get(@Paginate() query: PaginateQuery): Promise<Paginated<Game>> {
    return paginate(query, this.gamesRepository, {
      defaultLimit: 100,
      maxLimit: Number.MAX_SAFE_INTEGER,
      nullSort: "last",
      sortableColumns: [
        "id",
      ],
      withDeleted: false,
    });
  }
```
Response:
```json
{
    "data": [
        {
            "id": 1,
            <REDACTED>
        }
    ],
    "meta": {
        "itemsPerPage": 100,
        "totalItems": 372,
        "currentPage": 1,
        "totalPages": 4,
        "sortBy": [
            [
                "id",
                "ASC"
            ]
        ]
    },
    "links": {
        "current": "https://alfagun74.de/api/v1/games?page=1&limit=100&sortBy=id:ASC",
        "next": "https://alfagun74.de/api/v1/games?page=2&limit=100&sortBy=id:ASC",
        "last": "https://alfagun74.de/api/v1/games?page=4&limit=100&sortBy=id:ASC"
    }
}
```

**Comment by Alfagun74** [comment]
Oh hell, nevermind, it was my issue. 

I accidentally switched an Environment Variable and my typeorm ran off some mock data 🥲

**Comment by Alfagun74** [comment]
Nevermind again, issue exists with real Database too

**Comment by Alfagun74** [comment]
Using ``return await paginate(...`` instead of ``return paginate(...`` fixed my issue for now.

**Comment by Alfagun74** [comment]
@ppetzold hey, have you got any idea, what could be causing this? :(
Got a bunch of users complaining about the fact, that they cannot find anything using the filters.

**Comment by xMase** [comment]
Do you have test last version?

**Comment by Alfagun74** [comment]
Yes

xMase ***@***.***> schrieb am Do., 16. Feb. 2023, 02:47:

**Comment by xMase** [comment]
Try to disable this library:
 typeorm-naming-strategies 
If it work we are not compatible with that
