### ISSUE TITLE
Result set issues after upgrading to v4.7.0 

### ISSUE THREAD

**Issue by dkrantsberg** [ppetzold/nestjs-paginate#477]
It might be the same issue as [this](https://github.com/ppetzold/nestjs-paginate/issues/470) one. 
After upgrading to nestjs-paginate from v4.6.4 to v4.7.0 I've started seeing weird result set issues. 
I have a table `projects` with 21 records. When `limit=10` option is specified only 3 records are returned.

GET http://localhost:3333/api/projects?limit=10

<img width="760" alt="image" src="https://user-images.githubusercontent.com/1305115/217101276-6f2f036d-0ea2-44be-aecf-486eef58067c.png">

The generated PostgreSQL query is correct and returns correct records. So it's probably during the data mapping step when this error is happening. 

Dependencies:
```
node v16.18.1

"nestjs-paginate": "4.7.0",
"typeorm": "^0.3.11",
"@nestjs/typeorm": "^9.0.1",
"@nestjs/core": "^9.2.1",
```

**Comment by ppetzold** [comment]
@xMase hmm could this be possibly due to https://github.com/ppetzold/nestjs-paginate/commit/77494531d39f93f4f305172824070280ad8a57ac#diff-c58e144dadf00250381ed55e6ce83245cda76aca84131ad494fd4911932f656fR265 ?

**Comment by xMase** [comment]
can you provide an example project to test it?

**Comment by suleymankalkan** [comment]
I am having the same issue as well. (Typeorm)
