### ISSUE TITLE
#434 breaking searchBy for other field-types than text (postgres support)

### ISSUE THREAD

**Issue by jakobwgnr** [ppetzold/nestjs-paginate#485]
Hey! 
As mentioned in #434 this PR is breaking the searchBy functionality as case-sensitive field (e.g. lastName) are not covered by "".

Please find the error message below. 

WHERE (\"user\".\"deleted\" = $1) AND (user.firstName::text ILIKE $2 OR user.lastName::text ILIKE $3 OR user.email::text ILIKE $4 OR user.role::text ILIKE $5) ORDER BY \"user\".\"lastName\" ASC LIMIT 20","parameters":[false,"%SUPERADMIN%","%SUPERADMIN%","%SUPERADMIN%","%SUPERADMIN%"],"driverError":{"length":92,"name":"error","severity":"ERROR","code":"42601","position":"6513","file":"scan.l","line":"1180","routine":"scanner_yyerror"},"length":92,"severity":"ERROR","code":"42601","position":"6513","file":"scan.l","line":"1180","routine":"scanner_yyerror"}

**Comment by ppetzold** [comment]
Ok. I think I'll look into postgre coverage for CI. would imagine this does not only affect `search` but `filters` as well.

**Comment by ppetzold** [comment]
Happy if someone wants to work through the postgres issues. Just fork #486.

**Comment by ppetzold** [comment]
Closes by #544
