### ISSUE TITLE
Search in PostgreSQL doesn't work if column name is snake cased

### ISSUE THREAD

**Issue by ndrewnee** [ppetzold/nestjs-paginate#497]
Suppose we have entity

```ts
@Entity('admins')
export class AdminEntity {
    @Column({ type: 'text', name: 'last_name' })
    public lastName?: string;
}
```

And we query like this

```ts
const query = { searchBy: ['lastName'] };
await paginate(query, this.adminRepository, {
    searchableColumns: ['lastName'],
});
```

It returns SQL error `column e.lastname does not exist`

Generated SQL:

```sql
SELECT
	"e"."last_name" AS "e_last_name"
FROM
	"admins" "e"
WHERE
	((e.lastName::text ILIKE $1))
LIMIT
	10
```

I think it happens because in PostgreSQL [there's converting](https://github.com/ppetzold/nestjs-paginate/blob/dbf6786010b1c46ae84d08816b0cbbea41071e94/src/paginate.ts#L216) `lastName` to `lastName::text`.

And TypeORM can't resolve `lastName::text` to `last_name`.

**Comment by BekaDvali132** [comment]
Was there any update to this bug?

**Comment by jakobwgnr** [comment]
Hey @ndrewnee , @BekaDvali132 - The reason behind the issue has been identified here: #485 with several details.

Actually it has been fixed initially by me with #446 which has again been dropped again in favor of another feature with virtual columns
Didn't find time yet to work on it again, but feel free to use the information in this PR as a basis for giving it a shot yourself

**Comment by art1c0** [comment]
I have `firstName`column, which works in `sortableColumns`, but does not work in `searchableColumns`.
```
@Column({ type: 'varchar', length: 64, nullable: false })
firstName: string;
```
```
paginate(query, queryBuilder, {
  sortableColumns: [
    'id',
    'createdAt',
    'updatedAt',
    'firstName',
    'lastName',
  ],
  searchableColumns: ['email', 'phone', 'firstName', 'lastName'],
  defaultLimit: 10,
});
```

**Comment by its-monotype** [comment]
+1

**Comment by ppetzold** [comment]
Duplicate #485

**Comment by ndrewnee** [comment]
Well, it's kinda strange that you can use camelcase fields in `sortableColumns` but can't in `searchableColumns` like described in [this comment](https://github.com/ppetzold/nestjs-paginate/issues/497#issuecomment-1453423924).
But ok

**Comment by ppetzold** [comment]
See #544 somehow `::text` cast prevented typeorm to transform the query properly. `CAST() AS text` solved.
