### ISSUE TITLE
Is there an ArrayIncludes operator?

### ISSUE THREAD

**Issue by zkldi** [ppetzold/nestjs-paginate#534]
Hi, I have an entity that uses postgres's array fields as such:
```ts
enum Role { A = "A", B = "B", C = "C" }

@Entity('users')
export class User extends BaseEntity {
  @Index({ unique: true })
  @PrimaryGeneratedColumn({ name: 'id' })
  id: number;

  @Column({
    name: 'roles',
    type: 'enum',
    array: true,
    enum: Role,
    default: [Role.A],
  })
  roles: Role[];
}
```

How can we query this with things like `filter.roles=$includes:A`? We want to return all users where the array has `A` in it.

In Postgres there's the `@>` operator which does this, and in TypeORM I believe there's the `ArrayIncludes()` function. Is this functionality exposed via the paginate API anyhow, and if not, would a PR be accepted?

**Comment by ppetzold** [comment]
Yup, not exposed yet but would accept PR :) Needs to be mapped here:

https://github.com/ppetzold/nestjs-paginate/blob/master/src/operator.ts#L50

**Comment by zkldi** [comment]
PR up at #536
