### ISSUE TITLE
Can nest-paginate used with TableInheritance?

### ISSUE THREAD

**Issue by JonathanLoscalzo** [ppetzold/nestjs-paginate#554]
In case we want to work with @TableInheritance and @ChildEntity, is there a way to filter using childs?

e.g.

```
@Entity()
@TableInheritance({ column: { type: 'varchar', name: 'type' } })
export abstract class Leave
  extends EntityAuditableSoft
  implements SoftDeleteBaseEntity<string>, ILeave
{
  @Column()
  start: Date;

  @Column()
  end: Date;

  @ManyToOne(() => Employee, (employee) => employee.contacts, {
    cascade: false,
  })
  employee: Employee;
}

@ChildEntity('medical')
export class MedicalLeave extends Leave implements IMedicalLeave {
  @Column()
  diagnosis: string;

  @Column()
  doctor: string;

  @Column()
  hospital: string;

  @Column({ default: false })
  certificate: boolean;
}

.....

/ / and the paginate config 

{
      sortableColumns: ['id'],
      nullSort: 'last',
      searchableColumns: [
           "doctor", // it doesn't work
           "hospital" // it doesn't work
           "start", // it works
           "end", // it works
           ....
      ],
      defaultSortBy: [],
      filterableColumns: {
        'employee.id': [FilterOperator.EQ],
      },
      relations: ["employee"],
    });

```

**Comment by ppetzold** [comment]
don't see a reason why this wouldn't work - as it's the same table. what does not work? query wrong? or typings?

**Comment by JonathanLoscalzo** [comment]
I think that the typings works just for the parent entity (or the typing you are setting as generic)

```
export interface PaginateConfig<T> {
    relations?: RelationColumn<T>[];
    searchableColumns?: Column<T>[];
    filterableColumns?: {
        [key in Column<T>]?: FilterOperator[];
    };
    ....
}
```

I guess that `Column` type is just looking for keys on T (in this case, it is just `Leave` entity).

**Comment by ppetzold** [comment]
`paginate<MedicalLeave>(..)` doesn't work?

**Comment by JonathanLoscalzo** [comment]
`paginate<MedicalLeave>` just works for that subclass, but if I have other ones (like SpecialLeave or VacationLeave) I am not able to paginate all the leaves.

**Comment by ppetzold** [comment]
Seems like you just need to intersect the types you need somehow.. e.g.`paginate<MedicalLeave & SpecialLeave & VacationLeave>`, or just do `any` cast

**Comment by ppetzold** [comment]
@JonathanLoscalzo issue solved? can close?

**Comment by JonathanLoscalzo** [comment]
@ppetzold the typing correct works, but I don't have time to test the functionality. 
I will test it out later, but if you need to close it. In case I need more information I will reopen it. 
Thanks @ppetzold !

**Comment by JonathanLoscalzo** [comment]
@ppetzold I solve it with some workarounds.

- When I create child entities, We must use its own repositories

```
    @InjectRepository(Leave)
    private leaveRepository: Repository<LeaveFull>,

    @InjectRepository(MedicalLeave)
    private medicalLeaveRepo: Repository<MedicalLeave>,

    @InjectRepository(SpecialLeave)
    private specialLeaveRepo: Repository<SpecialLeave>,

    @InjectRepository(VacationLeave)
    private vacationLeaveRepo: Repository<VacationLeave>,
```

- for pagination, we could use `leaveRepository`, but it returns all the columns, so we can use a mapper o field filter by type in the future (or automapper)
- for dto's, I have created an entity with all the fields, and added a `type` field
    - I have used a switch to match which repository I must use (it could be a dictionary it's the same)
    - I don't know if it is possible to create 3 dto's and use a discriminator.
 
```
switch (entity.type) {
      case 'special':
        leave = SpecialLeave.from_dto(entity);
        return this.specialLeaveRepo.save({ ...leave, employee });
      case 'vacation':
        leave = VacationLeave.from_dto(entity);
        return this.vacationLeaveRepo.save({ ...leave, employee });
      case 'medical':
        leave = MedicalLeave.from_dto(entity);
        return this.medicalLeaveRepo.save({ ...leave, employee });
    }
```
