### ISSUE TITLE
query with limit provides exactly half of what has been given

### ISSUE THREAD

**Issue by jakobwgnr** [ppetzold/nestjs-paginate#565]
Hey!

I have a strange behaviour that a query provides exactly half of the entries that I've provided in the limit query param...
I'm currently using 7.1.0 and I recently upgraded from 4.6.3 - I guess this issue appeared when upgrading the package.

Any Idea? May I help?

Unfortunately the query wasn't logged... I don't really understand whats going on.

![image](https://user-images.githubusercontent.com/18501893/227795118-7527d42b-5e21-486e-953c-b4a708f988dc.png)

![image](https://user-images.githubusercontent.com/18501893/227795206-66fe5886-5957-4373-be32-082f50061e5a.png)

**Comment by ppetzold** [comment]
Found something. I knew there are side effects using limit/offset with joins. But always assumed this is an issue with the ORM. But this article explains well that this comes from SQL itself.

https://dncrews.com/limit-and-offset-can-work-with-join-f03327fa2ad3

Take/skip actually works like the proposed solution in the article. But in TypeORM it comes with others issues.

Need to play around with it next week if we can use the sub query limit/offset and have everything else work properly as well.

For now, you could change pagination type to take/skip.

**Comment by ppetzold** [comment]
Ok. Seems very cumbersome to solve on our own. Defaulting back to take/skip. Seems to work well with test suite for sqlite and postgres.
