### ISSUE TITLE
Column type infers the properties of a Promise instead of the relation properties (lazy loading)

### ISSUE THREAD

**Issue by izemomar** [ppetzold/nestjs-paginate#582]
I have encountered an issue with the **Column** type when working with entities that use lazy loading. Specifically, the Column type infers the properties of a Promise ( then , catch ... ) instead of the relation properties. This can cause type errors when accessing properties of the relation.

For example, consider the following entities:

```
@Entity({ name: 'cat' })
export class CatEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @OneToMany(() => CatToyEntity, catToy => catToy.cat, { lazy: true })
  toys: Promise<CatToyEntity[]>;
}

@Entity()
export class CatToyEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @Column(() => SizeEmbed)
  size: SizeEmbed;

  @ManyToOne(() => CatEntity, cat => cat.toys)
  @JoinColumn()
  cat: CatEntity;

  @CreateDateColumn()
  createdAt: string;
}
```

If I try to access a property of the relation using the Column type, I get a type error:
```
const cols: Column<CatEntity> = 'toys.name'; // Type '"toys.name"' is not assignable to type '"id" | "name" | "toys" ....
```

Here's how the actual issue looks like on my editor
![image](https://user-images.githubusercontent.com/59101683/231290524-5e2c4084-3feb-4619-b201-8505986b1c22.png)

I believe that the Column type should be updated to unwrap Promise properties with the UnwrapPromise helper type (To be created ). This would ensure that it works correctly with entities that use lazy loading.

**I would like to know if I can open a pull request to implement this fix. Thank you for your attention to this issue.**

**Comment by ppetzold** [comment]
Yep. Would accept PR 👋
