### ISSUE TITLE
How to easily generate the query string syntax in frontend?

### ISSUE THREAD

**Issue by cristobalgvera** [ppetzold/nestjs-paginate#697]
Hi guys, I'm wondering how to easily generate the syntax proposed by the library, e.g.: `...?filter.email=$sw:e`.

My concerns are related to the dollar notation (`filter.<attribute>=$<operator>:<value>`) used in filters.

Do you know if exists a library that helps to generate this kind of syntax, else what are you doing in order to create it?

Thanks!

**Comment by ppetzold** [comment]
should be all simple using string arrays and `.join()`, or to what problem are you referring to?
