### ISSUE TITLE
Swagger API annotations

### ISSUE THREAD

**Issue by vsamofal** [ppetzold/nestjs-paginate#708]
Hi guys, nice library. 

I'm implementing swagger generation for nestjs project that do use your lib for find all method. I think it will be useful to include it to this library, because it's general and I think everyone can benefit it. 

that's how it looks like 

![image](https://github.com/ppetzold/nestjs-paginate/assets/27850115/90a2b2b2-228e-40e0-a759-ae543d9144b9)

let me know if you think that it make sense to create a PR and include it into nestjs-paginated

**Comment by ppetzold** [comment]
yup I think we had an open issue for that. happy to accept PR and evaluate your implementation ;)

**Comment by vsamofal** [comment]
got it, I will close this one as duplicate then
