### ISSUE TITLE
Where clouse not worknig when using relations columns 

### ISSUE THREAD

**Issue by Loque18** [ppetzold/nestjs-paginate#717]
Hello, 

I'm facing an issue when trying to fetch items using the where clouse, but using a column from the relation

**Tables**
User
Items

**Relations** 
Users -> one to many -> item

**code** 

```ts
const paginatedResult = await paginate(query, this.itemRepository, {
    relations: ["user"],

    select: ["id", "name", "user.id", "user.username", "createdAt"],

    where: {
        user: { username },
    },

    sortableColumns: ["createdAt"],
    nullSort: "last",
    defaultSortBy: [["createdAt", "DESC"]],
    filterableColumns: {
        createdAt: [FilterOperator.GT, FilterOperator.LT],
    },
});
```

**Error**
Error: Cannot find alias for relation at user

**My conclusions**
I googled the error, and I find out that this is a typeorm error that happens when you use a relation column in a where clouse, wihtout specifying the relations, you can check the issue [here](https://github.com/typeorm/typeorm/issues/8310)

Am I doing something wrong or is this a bug?

Thanks in advance

**Comment by ppetzold** [comment]
umm, just checked. test suite only covers many-to-many for nested where. so could be a bug.

can you share the generated SQL query?

**Comment by Loque18** [comment]
> umm, just checked. test suite only covers many-to-many for nested where. so could be a bug.
> 
> can you share the generated SQL query?

Hello, thanks for your fast response, how can I get it ?

**Comment by Loque18** [comment]
I tried with the user id and it worked

**Comment by ppetzold** [comment]
ok closing this issue then
