### ISSUE TITLE
Roadmap ?

### ISSUE THREAD

**Issue by vladi-strilets** [ppetzold/nestjs-paginate#72]
Hi, this library looks awesome! 

I like that is so simple. without a ton of decorators and easy to implement. 
I've been using [nestjsx/crud](https://github.com/nestjsx/crud) and it's overwhelmed.

Are you planning to enhance it with new features? 
I would like to contribute some ideas and maybe even go ahead with them. 

What do you think about:

1. Serialize the data array
2. Nested filters 
3. Add relations from the query

**Comment by vladi-strilets** [comment]
With serialization, I mean filtering and transforming the response data. Using [class-transformer](https://github.com/typestack/class-transformer), for example. 

For now, in my code, I have implemented an interceptor (also could be a class or helper function) to catch the Paginated and call the `plainToClass()` for data param. Here I can provide a small example for the better understanding:

```
// controller

const paginatedResults = await paginate(...) // Item[]
return {
    ...paginatedResults,
    data: plainToClass(ItemResponseDto, paginatedResults.data)
}
```

```
// ItemResponseDto with class-transformer

@Exclude()
export class ItemResponseDto {
  @Expose()
  id: string;
...
}
```
-------
Having written this, I think this logic should be the responsibility of this module. So, nevermind  😅

**Comment by vladi-strilets** [comment]
And the idea behind the repository relations and nested filters is similar to the current implementation of the filterableColumn. 

The developer should be able to indicate the allowlist of routes to populate. 

**For example**
Entities:
`User - 1:N - Project - N:1 - City`

Paginate config prop:
`nestedRoutes: ['projects', 'projects.city']`

Query: 
`?join=projects,projects.city` 

----------

And over the same allowlist, it would be nice to have some filtering. 
For example, from the previous query, if I want to filter all users by project city population.
```
filterableColumns: {
        projects: {
          city: {
            population: [FilterOperator.GTE, FilterOperator.LTE]
          }
        },
        ...
      },
```
Query: 
`?filter.projects.city.population=$gte:100000`

**Comment by vladi-strilets** [comment]
And one more thing.

It would be nice to provide an extra query key `searchBy` to indicate on which column we should search.

What do you think?

**Comment by ppetzold** [comment]
Hi there 👋  Sorry for late response. Just came back from summer holiday.

All great proposals :) ! Happy to accept PRs. Let me put this into issues.

**Comment by ppetzold** [comment]
> And one more thing.
> 
> It would be nice to provide an extra query key `searchBy` to indicate on which column we should search.
> 
> What do you think?

Yup. Seems handy. By default search through all columns provided by `searchableColumns`; limit search query further by columns indicated in `searchBy`.
