### ISSUE TITLE
Config options to disable "searchBy" and "select" query parameters

### ISSUE THREAD

**Issue by holuborhee** [ppetzold/nestjs-paginate#773]
When creating REST API for frontend applications, oftentimes the backend does not want to leave the option of fields to return in result or fields to match query parameters.

I am proposing two config options, one each to prevent the use of the `searchBy` and `select` in the query parameters. Disabling either should prevent it from being considered in the SELECT query, the logic will then use the provided values for the `searchableColumns` and `select` config options.

Proposed option names are `disbaleSearchByInQueryParam` and `disableSelectInQueryParam` both should default to false, to match current behavior and allow for backward compatibility.

Current documentation for `searchableColumns` and `select` option is seen below 👇 

```
/**
   * Required: false
   * Type: (keyof CatEntity)[]
   * Description: These columns will be searched through when using the search query
   * param. Limit search scope further by using `searchBy` query param.
   */
  searchableColumns: ['name', 'color'],

  /**
   * Required: false
   * Type: (keyof CatEntity)[]
   * Default: None
   * Description: TypeORM partial selection. Limit selection further by using `select` query param.
   * https://typeorm.io/select-query-builder#partial-selection
   * Note: You must include the primary key in the selection.
   */
  select: ['id', 'name', 'color'],
```

It highlighted "Limit search scope further by using `searchBy` query param." and "Limit selection further by using `select` query param.". **This suggestion provides the option to prevent further limits on selection or search scope**

**Comment by ppetzold** [comment]
Yup. Sounds good to me. Happy to accept PR 👍

**Comment by holuborhee** [comment]
Issue fixed in this PR https://github.com/ppetzold/nestjs-paginate/pull/790 🚀
