### ISSUE TITLE
Nested Relation Doc obsolete or wrong?

### ISSUE THREAD

**Issue by v4ssi404** [ppetzold/nestjs-paginate#805]
https://github.com/ppetzold/nestjs-paginate#code-2

```
const config: PaginateConfig<CatEntity> = {
  relations: { home: { pillows: true } },
  ...
```

Is this `relations` object-like syntax obsolete or wrong maybe?

**Comment by vsamofal** [comment]
what is obsolete and why do you think it's wrong? 

if you set relations like this, typeorm will retrieve home and pillows info 
if you won't provided it won't be there

**Comment by v4ssi404** [comment]
Sorry for the late response, I was busy.

Probably was `node_modules` craziness after a version update.

I cannot reproduce it anymore, I will check on my other computer, anyway I was getting an error that was not accepting object notation.
