### ISSUE TITLE
Links Undefined

### ISSUE THREAD

**Issue by ryugif** [ppetzold/nestjs-paginate#84]
Hi, in my links section it contains undefined which should be app url, is there any option or maybe I miss something?
I've set APP_URL in .env but it's still undefined

![image](https://user-images.githubusercontent.com/42869239/133850867-11c5a6ed-c838-475b-93fb-9c709eb77a51.png)

This is my service
```javascript
async getChatNotification(query: PaginateQuery): Promise<Paginated<ChatNotificationEntity>> {
  return paginate(query, this.chatNotification, {
    where: { deleted_at: null },
    sortableColumns: ['id', 'title', 'type', 'content', 'read_at'],
    searchableColumns: ['id', 'title', 'type', 'shop_id', 'content', 'read_at'],
    defaultSortBy: [['id', 'DESC']],
  })
}
```

**Comment by ppetzold** [comment]
Do you use express with nestjs? It likely would have those kind of issues when using other web frameworks such as fastify.

https://github.com/ppetzold/nestjs-paginate/blob/master/src/decorator.ts#L17

**Comment by ryugif** [comment]
Yes, I'm using nestjs with express

**Comment by ppetzold** [comment]
That's odd. Are you using the decorator properly? What values does `query` contain when being passed onto `paginate`?

**Comment by ryugif** [comment]
Hi @ppetzold sorry for late reply, I'm switching to WSL and the problem is gone. I don't know why on Windows it's undefined, I've tried to create the project from scratch again but it's still undefined in the links section.

**Comment by Helveg** [comment]
Could this issue be reopened? I'm having the same problem, also on a Windows machine!

**Comment by Helveg** [comment]
```typescript
  @Get()
  findAll(@Query() query: PaginateQuery) {
    return this.platformsService.findAll(query);
  }
```

```

```typescript
  findAll(query: PaginateQuery): Promise<Paginated<Platform>> {
    return paginate(query, this.platformRepo, {
      sortableColumns: ["short_name"],
      searchableColumns: ["name", "short_name"],
      defaultLimit: 20,
      defaultSortBy: [["short_name", "ASC"]]
    });
  }
  ```
  
The value of `query` is `{}`, I didn't pass any params to the request.

**Comment by ppetzold** [comment]
@Helveg hmm `path` should be present. could you debug the decorator why it's not correctly read from the request?

**Comment by Helveg** [comment]
It's windows only and an easy workaround exists, but if it comes up in the backlog I'll take a look!

```
  @Get()
  findAll(@Query() query: PaginateQuery, @Req() request) {
    query.path = request.protocol + '://' + request.get('host') + request.originalUrl;
    return this.dataService.findAll(query);
  }
```

**Comment by ppetzold** [comment]
closing for now

**Comment by Helveg** [comment]
Well, turns out I was missing the the `@Paginate` decorator!
