### ISSUE TITLE
SortBy property likely not functioning correctly

### ISSUE THREAD

**Issue by Razac6** [ppetzold/nestjs-paginate#853]
Hello!
Thank you for the awesome library.
I'm having some trouble with sorting. I'm not sure, but it seems like it's not working correctly. I created a configuration based on the documentation like this:

```
export const CustomerConfigPaginate: PaginateConfig<Entity> = {
  defaultLimit: 10,
  defaultSortBy: [['customerName', 'ASC']],
  filterableColumns: {
    customerName: true
  },
  maxLimit: 20,
  searchableColumns: ['customerName'],
  sortableColumns: ['customerName', 'id']
};
```

But when I try to call with the sortBy parameter
like this:
{{baseUrl}}/api/customers?ExampleKey={{apiKey}}&sortBy=customerName:DESC

it's not working (return defaultSortBy). I investigated and I see that for some reason it expects an array. So, I created mappers,

something like this:

```
export class PaginationQueryMapper {
  static createUpdatedQuery(query: CustomPaginateQuery): PaginateQuery {
    const transformedSortBy = this.queryTransform(query.sortBy ?? '');
    return { ...query, sortBy: transformedSortBy };
  }

  private static queryTransform(query: string): [string, 'ASC' | 'DESC'][] {
    const parts = query.split(':');
    const [column, direction] = parts;
    return [[column, direction as 'ASC' | 'DESC']];
  }
}
```

But I'm not sure if it's a bug or if I'm doing something wrong.

Thanks !

**Comment by ppetzold** [comment]
You mean to say that the `@Paginate()` decorator is not parsing `sortBy` as a 2D array?

**Comment by mbinek-fadv** [comment]
You are right, everything works correctly. By mistake, I used @Query instead of @Pagination.
Thanks !

**Comment by Razac6** [comment]
You are right, everything works correctly. By mistake, I used @Query instead of @Pagination.
Thanks !
