### ISSUE TITLE
Type of `where` should allow array of objects as well

### ISSUE THREAD

**Issue by bartosjiri** [ppetzold/nestjs-paginate#87]
According to [TypeORM docs](https://typeorm.io/#/find-options), the `where` find option should also support an array of options to apply an OR operator:
```
userRepository.find({
    where: [
        { firstName: "Timber", lastName: "Saw" },
        { firstName: "Stan", lastName: "Lee" },
    ],
});

-> SELECT * FROM "user" WHERE ("firstName" = 'Timber' AND "lastName" = 'Saw') OR ("firstName" = 'Stan' AND "lastName" = 'Lee')
```

Providining such array however results in the following TS error for me:
```
Type '({ property1: value1; } | { property2: value2; })[]' has no properties in common with type 'FindConditions<Entity>'.
```

Is this an error on my side or does the library not support this feature?

**Comment by ppetzold** [comment]
Oh, you are right. Fixed it :)

https://github.com/ppetzold/nestjs-paginate/pull/88
