### ISSUE TITLE
select show all columns when no primary key provided

### ISSUE THREAD

**Issue by awaismehmood88** [ppetzold/nestjs-paginate#875]
When selecting column from query string without primary key, All the columns of entity and relation entity shows even those columns not included in configurations.

**Comment by ppetzold** [comment]
oh that sounds bad (at least if this affects the select query param). I know we have a code comment that primary key is required. but I suppose no coverage to check for security issues if not provided.

quite packed this week. appreciate any contributions for fixing this issue

**Comment by awaismehmood88** [comment]
Pull request #879 Fix this issue please review and merge. @ppetzold
