### ISSUE TITLE
How to do i sort naturally instead of alphabetically?

### ISSUE THREAD

**Issue by Alfagun74** [ppetzold/nestjs-paginate#907]
Currently, when sorting, let's say, by a field called "title", it is only possible to sort purely alphabetically. In a list of games, in my case, for example, it means the 10th element comes after the 1st one:

```
Jackbox Party Pack 1
Jackbox Party Pack 10
Jackbox Party Pack 2
Jackbox Party Pack 3
Jackbox Party Pack 4
Jackbox Party Pack 5
Jackbox Party Pack 6
Jackbox Party Pack 7
Jackbox Party Pack 8
Jackbox Party Pack 9
```

Would it be possible to run an [Natural sorting method](https://en.wikipedia.org/wiki/Natural_sort_order) by doing something like [this approach](https://stackoverflow.com/a/16520873) using this library?

So the end result would be:

```
Jackbox Party Pack 1
Jackbox Party Pack 2
Jackbox Party Pack 3
Jackbox Party Pack 4
Jackbox Party Pack 5
Jackbox Party Pack 6
Jackbox Party Pack 7
Jackbox Party Pack 8
Jackbox Party Pack 9
Jackbox Party Pack 10
```

Has anybody already encountered this problem and might want to share their approach?

**Comment by Helveg** [comment]
It doesn't seem like this is something that TypeORM supports out of the box.

Using the approach you linked would not work as-is:

```
Z
Ab 1
Ab 10
```

note how `Z` would be sorted before `Ab 1` because of its length?

If you can figure out what you need using the `QueryBuilder` API, then you can also pass a `QueryBuilder` into `paginate`, instead of the repository.

**Comment by Alfagun74** [comment]
You're right. I can't find an easy way to do this properly honestly.

**Comment by Helveg** [comment]
It seems like indeed at the SQL level the world hasn't really settled onto a solution yet. Take a look at the lengths this answer tries to go: https://stackoverflow.com/a/58154535/1016004

**Comment by Alfagun74** [comment]
yeah fuck this totally.
