### ISSUE TITLE
FilterOperator.CONTAINS is BUG in postgresql ?

### ISSUE THREAD

**Issue by KhoiBec** [ppetzold/nestjs-paginate#936]
sorry about my english
my entity column 
`  @Column({
    type: 'enum',
    enum: RoleType,
    default: [RoleType.USER],
    array: true,
  })
  roles!: RoleType[];`

` if (isArray && condition.parameters?.length && !['not', 'isNull'].includes(condition.operator)) {
            condition.parameters[0] = `cardinality(${condition.parameters[0]})`
        }`

`cardinality` returns the total number of elements in the array so filter contains will not work ?

**Comment by Helveg** [comment]
Hi! Thanks for reporting this issue! Could you show us with a full code example what the problem is? How are you using `nestjs-paginate`, what output or error do you get, and what output did you expect?

**Comment by ppetzold** [comment]
ideally submit a test case as PR pls
