### ISSUE TITLE
Case insensitive filter values

### ISSUE THREAD

**Issue by wisac** [ppetzold/nestjs-paginate#964]
Is there a way to make filter field values case-insensitive?
By default   `/users?filter.firstName=john` would return ZERO result if you have `John` or` JOHN` instead of `john` in the database.

**Comment by Helveg** [comment]
You can use the `$ilike` operator! :)

**Comment by Helveg** [comment]
@wisac does this address your issue?

**Comment by wisac** [comment]
I had wanted to go with the collation setting like you suggested since it looks straightforward.

I did some digging and found that in `postgres`, the collation setting can be achieved by using the `citext` datatype or creating collation on esch column. This will require altering of tables and data migration. (I tried it)

Using the `$ilike` operator, looks like the best option I've got but it would return other values too.
Eg. `firstName=$ilike:john` would return `John-Smith` too.

I have many tables with many fields I want to be queryable. 

So I'm still looking at various options

**Comment by Helveg** [comment]
Ok, good to know! I'll consider this issue closed then. Feel free to write a summary when you've found a solution that suited all your needs, that way future visitors can benefit! If you find that a good solution is not possible with `nestjs-paginate`, feel free to reopen the issue 👍
