### ISSUE TITLE
`instanceof` checks fail during certain issues with peer dependencies

### ISSUE THREAD

**Issue by Helveg** [ppetzold/nestjs-paginate#966]
Sometimes, under less-than-clean `npm` conditions, `npm` installs multiple isolated `typeorm` packages, and `nestjs-paginate` ends up using a different one from the main build. In that case, all the `typeorm` related `instanceof` checks (3) fail:

```
repo instanceof Repository
```

fails, because the user passed in a `Repository` from _their_ `typeorm`, call it `typeorm-a`, while `nestjs-paginate` has imported `Repository` from `typeorm-b`. I can submit a PR to convert these 3 `instanceof` checks to something like:

```
function isRepository(repo: unknown): repo is Repository {
  if (repo instanceof Repository) return true;
  try {
    if (Object.getPrototype(repo).constructor.name === "Repository")
      return true;
    return !('connection' in repo) && 'manager' in repo,
  } catch {
    return false
  }
}
```

**Comment by ppetzold** [comment]
LGTM
