### ISSUE TITLE
How to use multiple filters with $and and $or

### ISSUE THREAD

**Issue by wisac** [ppetzold/nestjs-paginate#996]
How do i achieve this logic with filter? 
`(name=john AND age=5) OR (name=john AND age=10)`.

I'm struggling with the how to use multiple filters.
If anyone could provide a little explanation on how to achieve this, I would be very grateful.
Thanks 😊

**Comment by Helveg** [comment]
Closing this in favor of your discussion: https://github.com/ppetzold/nestjs-paginate/discussions/995

Feel free to reopen if you'd like to elevate this question into a feature request, especially if you'd have the time to develop it 🤗
